### Get all agents
GET {{api-server}}/v2/agents
X-Api-Key: {{read-only-token}}

### Get all agents of class
GET {{api-server}}/v2/agents/iosys
X-Api-Key: {{read-only-token}}

### Insert new agent for class
POST {{api-server}}/v2/agents/iosys
X-Api-Key: {{read-write-token}}
Content-Type: application/json

{
  "description": "IOSYS Agent east plant",
  "enable": false,
  "config": {}
}

### Get agent
GET {{api-server}}/v2/agents/iosys/4
X-Api-Key: {{read-only-token}}

### Update new agent for class and id
PUT {{api-server}}/v2/agents/iosys/4
Content-Type: application/json
X-Api-Key: {{read-write-token}}

{
  "description": "IOSYS Agent east plant (updated)",
  "enable": false,
  "config": {}
}



### Select devices
GET {{api-server}}/v2/agents/iosys/4/devices
X-Api-Key: {{read-only-token}}

### Select device
GET {{api-server}}/v2/agent-devices/iosys/4
X-Api-Key: {{read-only-token}}

### Insert devices
POST {{api-server}}/v2/agents/iosys/4/devices
X-Api-Key: {{read-write-token}}
Content-Type: application/json

{
  "enable": false,
  "port": 0,
  "certificate": "XXX",
  "key": "YYY",
  "timeout": 0,
  "reconnect": 20
}

### UPDATE devices
PUT {{api-server}}/v2/agent-devices/iosys/4
X-Api-Key: {{read-write-token}}
Content-Type: application/json

{
  "enable": false,
  "port": 0,
  "certificate": "XXX (updated)",
  "key": "YYY (updated)",
  "timeout": 0,
  "reconnect": 20
}



### Select mappings
GET {{api-server}}/v2/agent-devices/iosys/4/mappings
X-Api-Key: {{read-only-token}}

### Select mapping
GET {{api-server}}/v2/agent-device-mappings/iosys/1
X-Api-Key: {{read-only-token}}

### Insert mapping
POST {{api-server}}/v2/agent-devices/iosys/4/mappings
X-Api-Key: {{read-write-token}}
Content-Type: application/json

{
  "enable": true,
  "subtype": "input",
  "attribute": "temperature",
  "iosVar": "string",
  "iosType": "INT",
  "down": false,
  "scale": 0,
  "zero": 0,
  "deadTime": 0,
  "deadBand": 0,
  "filter": "LPF1",
  "tau": 0
}

### Update mapping
PUT {{api-server}}/v2/agent-device-mappings/iosys/1
X-Api-Key: {{read-write-token}}
Content-Type: application/json

{
  "deviceId": 4,
  "enable": true,
  "subtype": "input",
  "attribute": "temperature",
  "iosVar": "string (updated)",
  "iosType": "INT",
  "down": false,
  "scale": 0,
  "zero": 0,
  "deadTime": 0,
  "deadBand": 0,
  "filter": "LPF1",
  "tau": 0
}