### [Agents] List all IOSYS agents (read-only)
GET {{api-server}}/v2/agents/iosys HTTP/1.1
X-Api-Key: {{read-only-token}}

### [Agents] Create a new IOSYS agent (read–write)
POST {{api-server}}/v2/agents/iosys HTTP/1.1
X-Api-Key: {{read-write-token}}
Content-Type: application/json

{
  "assetId": 62682,
  "description": "New IOSYS agent for East Plant",
  "class": "iosys",
  "enable": true,
  "config": {
    "ip": "192.168.0.10",
    "port": 8080
  }
}

### [Agents] Get agent by class and id with optional expansions (read-only)
GET {{api-server}}/v2/agents/iosys/336 HTTP/1.1
X-Api-Key: {{read-only-token}}

### [Agents] Update an agent (read–write)
PUT {{api-server}}/v2/agents/iosys/336 HTTP/1.1
X-Api-Key: {{read-write-token}}
Content-Type: application/json

{
  "assetId": 62682,
  "description": "Updated IOSYS agent: now with enhanced monitoring",
  "class": "iosys",
  "enable": true,
  "config": {
    "ip": "192.168.0.10",
    "port": 8080,
    "monitoringInterval": 60
  }
}

### [Agents] List devices for an agent with paging (read-only)
GET {{api-server}}/v2/agents/iosys/336/devices HTTP/1.1
X-Api-Key: {{read-only-token}}

### [Agents] Create a new device for an agent (read–write)
POST {{api-server}}/v2/agents/iosys/336/devices HTTP/1.1
X-Api-Key: {{read-write-token}}
Content-Type: application/json

{
  "enable": true,
  "class": "iosys",
  "certificate": "CERTIFICATE",
  "key": "PRIVATE",
  "port": 15,
  "timeout": 30,
  "reconnect": 10
}
