### Get all aggregations
GET {{api-server}}/v2/aggregations
X-Api-Key: {{read-only-token}}

### Creates an aggregation
PUT {{api-server}}/v2/aggregations
X-Api-Key: {{read-write-token}}
Content-Type: application/json

{
    "assetId": 127,
    "subtype": "output",
    "mode": "avg",
    "raster": "MONTH"
}

### Updates an aggregation
PUT {{api-server}}/v2/aggregations/797
X-Api-Key: {{read-write-token}}
Content-Type: application/json

{
  "assetId": 127,
  "subtype": "output",
  "mode": "avg",
  "raster": "MONTH"
}

### Post an aggregation
POST {{api-server}}/v2/aggregations
X-Api-Key: {{read-write-token}}
Content-Type: application/json

{
  "assetId": 127,
  "subtype": "output",
  "mode": "avg",
  "raster": "MONTH"
}