### Get all aggregations
GET http://localhost:8084/v2/aggregations

### Creates an aggregation
PUT http://localhost:8084/v2/aggregations
Content-Type: application/json

{
    "assetId": 57006,
    "subtype": "output",
    "mode": "avg",
    "raster": "MONTH"
}
