### [Alarm rules] List alarm rules (read-only)
GET {{api-server}}/v2/alarm-rules?expansions=AlarmRule.assetInfo HTTP/1.1
X-Api-Key: {{read-only-token}}

### [Alarm rules] List alarm rules with filter parameters (read-only)
GET {{api-server}}/v2/alarm-rules?assetId=61894&alarmRuleIds=4621,4620&expansions=AlarmRule.assetInfo HTTP/1.1
X-Api-Key: {{read-only-token}}

### [Alarm rules] Create a new alarm rule with detailed parameters (read–write)
POST {{api-server}}/v2/alarm-rules HTTP/1.1
X-Api-Key: {{read-write-token}}
Content-Type: application/json

{
  "assetId": 61894,
  "subtype": "input",
  "attribute": "temperature",
  "enable": true,
  "priority": 2,
  "requiresAcknowledge": false,
  "equal": 38.7,
  "low": 38.0,
  "high": 39.5,
  "message": {
    "come": {
      "en": "Warning: Temperature out of range!"
    },
    "fallback": {
      "en": "Please check the sensor."
    }
  },
  "tags": ["critical", "sensor"],
  "notifyOn": "R",
  "dontMask": false
}

### [Alarm rules] Get an alarm rule by id with expansions (read-only)
GET {{api-server}}/v2/alarm-rules/4623?expansions=AlarmRule.assetInfo HTTP/1.1
X-Api-Key: {{read-only-token}}

### [Alarm rules] Update an alarm rule (read–write)
PUT {{api-server}}/v2/alarm-rules/4623 HTTP/1.1
X-Api-Key: {{read-write-token}}
Content-Type: application/json

{
  "assetId": 61894,
  "subtype": "input",
  "attribute": "temperature",
  "enable": true,
  "priority": 1,
  "requiresAcknowledge": true,
  "equal": 39.0,
  "low": 38.5,
  "high": 40.0,
  "message": {
    "come": {
      "en": "Critical: Temperature threshold exceeded"
    }
  },
  "tags": ["critical", "update"],
  "notifyOn": "R",
  "dontMask": false
}

### [Alarm rules] Delete an alarm rule by id (read–write)
DELETE {{api-server}}/v2/alarm-rules/4623 HTTP/1.1
X-Api-Key: {{read-write-token}}