### [Alarms] List alarms (read-only)
GET {{api-server}}/v2/alarms?expansions=Alarm.assetInfo,Alarm.ruleInfo,Alarm.acknowledgeUserInfo HTTP/1.1
X-Api-Key: {{read-only-token}}

### [Alarms] List alarms with tag filter and date filters (read-only)
GET {{api-server}}/v2/alarms?projectId=99&fromDate=2025-01-01T09:00:00.000Z&toDate=2025-12-31T23:00:00.000Z&tags=critical,warning&expansions=Alarm.assetInfo HTTP/1.1
X-Api-Key: {{read-only-token}}

### [Alarms] Acknowledge an alarm (using PATCH) with additional parameters (read–write)
PATCH {{api-server}}/v2/alarms/4618?acknowledged=true&acknowledgeText=Operator%20has%20checked%20the%20issue HTTP/1.1
X-Api-Key: {{read-write-token}}
Content-Type: application/json

### [Alarms] Mark an alarm as gone (DELETE) (read–write)
DELETE {{api-server}}/v2/alarms/4618 HTTP/1.1
X-Api-Key: {{read-write-token}}