### Update 111 assets in bulk for performance testing
# @timeout 600
PUT {{api-server}}/v2/assets-bulk
X-Api-Key: {{read-write-token}}
Content-Type: application/json

[
  {
    "projectId": "404",
    "globalAssetIdentifier": "TestWorld",
    "name": "World",
    "assetType": "Space"
  },
  {
    "projectId": "404",
    "globalAssetIdentifier": "TestContinent_Africa",
    "name": "Africa",
    "assetType": "Space",
    "parentLocationalIdentifier": "TestWorld",
    "parentFunctionalIdentifier": "TestWorld"
  },
  {
    "projectId": "404",
    "globalAssetIdentifier": "TestContinent_Asia",
    "name": "Asia",
    "assetType": "Space",
    "parentLocationalIdentifier": "TestWorld",
    "parentFunctionalIdentifier": "TestWorld"
  },
  {
    "projectId": "404",
    "globalAssetIdentifier": "TestContinent_Europe",
    "name": "Europe",
    "assetType": "Space",
    "parentLocationalIdentifier": "TestWorld",
    "parentFunctionalIdentifier": "TestWorld"
  },
  {
    "projectId": "404",
    "globalAssetIdentifier": "TestContinent_Americas",
    "name": "Americas",
    "assetType": "Space",
    "parentLocationalIdentifier": "TestWorld",
    "parentFunctionalIdentifier": "TestWorld"
  },
  {
    "projectId": "404",
    "globalAssetIdentifier": "TestContinent_Oceania",
    "name": "Oceania",
    "assetType": "Space",
    "parentLocationalIdentifier": "TestWorld",
    "parentFunctionalIdentifier": "TestWorld"
  },
  {
    "projectId": "404",
    "globalAssetIdentifier": "TestCountry_Afghanistan",
    "name": "Afghanistan",
    "assetType": "Space",
    "parentLocationalIdentifier": "TestContinent_Africa",
    "parentFunctionalIdentifier": "TestWorld"
  },
  {
    "projectId": "404",
    "globalAssetIdentifier": "TestCapital_Kabul",
    "name": "Kabul",
    "assetType": "Space",
    "parentLocationalIdentifier": "TestCountry_Afghanistan",
    "parentFunctionalIdentifier": "TestCountry_Afghanistan"
  },
  {
    "projectId": "404",
    "globalAssetIdentifier": "TestState_Afghanistan_State1",
    "name": "Afghanistan State 1",
    "assetType": "Space",
    "parentLocationalIdentifier": "TestCountry_Afghanistan",
    "parentFunctionalIdentifier": "TestCountry_Afghanistan"
  },
  {
    "projectId": "404",
    "globalAssetIdentifier": "TestState_Afghanistan_State2",
    "name": "Afghanistan State 2",
    "assetType": "Space",
    "parentLocationalIdentifier": "TestCountry_Afghanistan",
    "parentFunctionalIdentifier": "TestCountry_Afghanistan"
  },
  {
    "projectId": "404",
    "globalAssetIdentifier": "TestState_Afghanistan_State3",
    "name": "Afghanistan State 3",
    "assetType": "Space",
    "parentLocationalIdentifier": "TestCountry_Afghanistan",
    "parentFunctionalIdentifier": "TestCountry_Afghanistan"
  },
  {
    "projectId": "404",
    "globalAssetIdentifier": "TestCountry_Albania",
    "name": "Albania",
    "assetType": "Space",
    "parentLocationalIdentifier": "TestContinent_Asia",
    "parentFunctionalIdentifier": "TestWorld"
  },
  {
    "projectId": "404",
    "globalAssetIdentifier": "TestCapital_Tirana",
    "name": "Tirana",
    "assetType": "Space",
    "parentLocationalIdentifier": "TestCountry_Albania",
    "parentFunctionalIdentifier": "TestCountry_Albania"
  },
  {
    "projectId": "404",
    "globalAssetIdentifier": "TestState_Albania_State1",
    "name": "Albania State 1",
    "assetType": "Space",
    "parentLocationalIdentifier": "TestCountry_Albania",
    "parentFunctionalIdentifier": "TestCountry_Albania"
  },
  {
    "projectId": "404",
    "globalAssetIdentifier": "TestState_Albania_State2",
    "name": "Albania State 2",
    "assetType": "Space",
    "parentLocationalIdentifier": "TestCountry_Albania",
    "parentFunctionalIdentifier": "TestCountry_Albania"
  },
  {
    "projectId": "404",
    "globalAssetIdentifier": "TestState_Albania_State3",
    "name": "Albania State 3",
    "assetType": "Space",
    "parentLocationalIdentifier": "TestCountry_Albania",
    "parentFunctionalIdentifier": "TestCountry_Albania"
  },
  {
    "projectId": "404",
    "globalAssetIdentifier": "TestCountry_Algeria",
    "name": "Algeria",
    "assetType": "Space",
    "parentLocationalIdentifier": "TestContinent_Europe",
    "parentFunctionalIdentifier": "TestWorld"
  },
  {
    "projectId": "404",
    "globalAssetIdentifier": "TestCapital_Algiers",
    "name": "Algiers",
    "assetType": "Space",
    "parentLocationalIdentifier": "TestCountry_Algeria",
    "parentFunctionalIdentifier": "TestCountry_Algeria"
  },
  {
    "projectId": "404",
    "globalAssetIdentifier": "TestState_Algeria_State1",
    "name": "Algeria State 1",
    "assetType": "Space",
    "parentLocationalIdentifier": "TestCountry_Algeria",
    "parentFunctionalIdentifier": "TestCountry_Algeria"
  },
  {
    "projectId": "404",
    "globalAssetIdentifier": "TestState_Algeria_State2",
    "name": "Algeria State 2",
    "assetType": "Space",
    "parentLocationalIdentifier": "TestCountry_Algeria",
    "parentFunctionalIdentifier": "TestCountry_Algeria"
  },
  {
    "projectId": "404",
    "globalAssetIdentifier": "TestState_Algeria_State3",
    "name": "Algeria State 3",
    "assetType": "Space",
    "parentLocationalIdentifier": "TestCountry_Algeria",
    "parentFunctionalIdentifier": "TestCountry_Algeria"
  },
  {
    "projectId": "404",
    "globalAssetIdentifier": "TestCountry_Andorra",
    "name": "Andorra",
    "assetType": "Space",
    "parentLocationalIdentifier": "TestContinent_Americas",
    "parentFunctionalIdentifier": "TestWorld"
  },
  {
    "projectId": "404",
    "globalAssetIdentifier": "TestCapital_AndorralaVella",
    "name": "Andorra la Vella",
    "assetType": "Space",
    "parentLocationalIdentifier": "TestCountry_Andorra",
    "parentFunctionalIdentifier": "TestCountry_Andorra"
  },
  {
    "projectId": "404",
    "globalAssetIdentifier": "TestState_Andorra_State1",
    "name": "Andorra State 1",
    "assetType": "Space",
    "parentLocationalIdentifier": "TestCountry_Andorra",
    "parentFunctionalIdentifier": "TestCountry_Andorra"
  },
  {
    "projectId": "404",
    "globalAssetIdentifier": "TestState_Andorra_State2",
    "name": "Andorra State 2",
    "assetType": "Space",
    "parentLocationalIdentifier": "TestCountry_Andorra",
    "parentFunctionalIdentifier": "TestCountry_Andorra"
  },
  {
    "projectId": "404",
    "globalAssetIdentifier": "TestState_Andorra_State3",
    "name": "Andorra State 3",
    "assetType": "Space",
    "parentLocationalIdentifier": "TestCountry_Andorra",
    "parentFunctionalIdentifier": "TestCountry_Andorra"
  },
  {
    "projectId": "404",
    "globalAssetIdentifier": "TestCountry_Angola",
    "name": "Angola",
    "assetType": "Space",
    "parentLocationalIdentifier": "TestContinent_Oceania",
    "parentFunctionalIdentifier": "TestWorld"
  },
  {
    "projectId": "404",
    "globalAssetIdentifier": "TestCapital_Luanda",
    "name": "Luanda",
    "assetType": "Space",
    "parentLocationalIdentifier": "TestCountry_Angola",
    "parentFunctionalIdentifier": "TestCountry_Angola"
  },
  {
    "projectId": "404",
    "globalAssetIdentifier": "TestState_Angola_State1",
    "name": "Angola State 1",
    "assetType": "Space",
    "parentLocationalIdentifier": "TestCountry_Angola",
    "parentFunctionalIdentifier": "TestCountry_Angola"
  },
  {
    "projectId": "404",
    "globalAssetIdentifier": "TestState_Angola_State2",
    "name": "Angola State 2",
    "assetType": "Space",
    "parentLocationalIdentifier": "TestCountry_Angola",
    "parentFunctionalIdentifier": "TestCountry_Angola"
  },
  {
    "projectId": "404",
    "globalAssetIdentifier": "TestState_Angola_State3",
    "name": "Angola State 3",
    "assetType": "Space",
    "parentLocationalIdentifier": "TestCountry_Angola",
    "parentFunctionalIdentifier": "TestCountry_Angola"
  },
  {
    "projectId": "404",
    "globalAssetIdentifier": "TestCountry_AntiguaandBarbuda",
    "name": "Antigua and Barbuda",
    "assetType": "Space",
    "parentLocationalIdentifier": "TestContinent_Africa",
    "parentFunctionalIdentifier": "TestWorld"
  }
]