### Select assets
GET {{api-server}}/v2/assets
X-Api-Key: {{read-write-token}}

### Select asset with id
GET {{api-server}}/v2/assets/7
X-Api-Key: {{read-write-token}}

### Select asset with id and attachments
GET {{api-server}}/v2/assets?expansions=Asset.attributes
X-Api-Key: {{read-only-token}}

### Select asset with id and attachments
GET {{api-server}}/v2/attribute-display
X-Api-Key: {{read-only-token}}

### Upserts asset by project and gai
PUT {{api-server}}/v2/assets
X-Api-Key: {{read-write-token}}
Content-Type: application/json

{
  "projectId": "404",
  "globalAssetIdentifier": "GAI 4711112 404 3",
  "name": "Test Asset",
  "assetType": "Space",
  "parentFunctionalAssetId": 47724
}

### Insert asset
POST {{api-server}}/v2/assets
X-Api-Key: {{read-write-token}}
Content-Type: application/json

{
  "projectId": "10",
  "globalAssetIdentifier": "1234567890",
  "name": "Test Asset",
  "assetType": "Space"
}

### Update asset
PUT {{api-server}}/v2/assets
X-Api-Key: {{read-write-token}}
Content-Type: application/json

{
  "projectId": "10",
  "globalAssetIdentifier": "1234567890",
  "name": "Test Asset 1",
  "assetType": "Space"
}

### Insert asset with attachment
POST {{api-server}}/v2/assets?expansions=Asset.attachments
X-Api-Key: {{read-write-token}}
Content-Type: application/json

{
  "projectId": "99",
  "globalAssetIdentifier": "12345",
  "name": "Test Asset",
  "assetType": "thingdust_space",
  "attachments": [
    {
      "name": "example.gif",
      "encoding": "base64",
      "contentType": "image/png",
      "content": "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII="
    }
  ]
}

### Update new asset
PUT {{api-server}}/v2/assets/255
X-Api-Key: {{read-write-token}}
Content-Type: application/json

{
  "projectId": "99",
  "globalAssetIdentifier": "GAI 4711",
  "name": "Test Asset",
  "assetType": "weather_location"
}

### Update new asset with attachment
PUT {{api-server}}/v2/assets/255?expansions=Asset.attachments
X-Api-Key: {{read-write-token}}
Content-Type: application/json

{
  "projectId": "404",
  "globalAssetIdentifier": "GAI 4711#1",
  "name": "Test Asset",
  "assetType": "Space",
  "attachments": [
    {
      "name": "example.gif",
      "encoding": "base64",
      "contentType": "image/png",
      "content": "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII="
    }
  ]
}


### Update new asset in bulk
PUT {{api-server}}/v2/assets-bulk
X-Api-Key: {{read-write-token}}
Content-Type: application/json

[
  {
    "projectId": "404",
    "globalAssetIdentifier": "GAI 4711",
    "name": "Test Asset",
    "assetType": "VIRTUAL Light"
  },
  {
    "projectId": "404",
    "globalAssetIdentifier": "GAI 4712",
    "name": "Test Asset",
    "assetType": "VIRTUAL Light",
    "parentFunctionalIdentifier": "GAI 4711"
  }
]