### Delete type
DELETE http://localhost:8084/v2/asset-types/weather_location

### Insert new asset type
GET http://localhost:8084/v2/asset-types/weather_location

### Insert new asset type
PUT http://localhost:8084/v2/asset-types
Content-Type: application/json

{
"vendor": "vendor",
"custom": true,
"name": "weather_location",
"translation": {
"de": "Das ist eine deutsche Beschreibung",
"en": "This is an english description",
"it": "Questa è una descrizione italiana",
"fr": "Ceci est une description français"
},
"icon": "weather",
"urldoc": "urldoc",
"model": "model"
}