### Get type
GET {{api-server}}/v2/asset-types/abb_free_at_home_switch_sensor?expansions=AssetType.attributes
X-Api-Key: {{read-write-token}}

### Delete type
DELETE {{api-server}}/v2/asset-types/
X-Api-Key: {{read-write-token}}

### Selects asset type
GET {{api-server}}/v2/asset-types/test_asset_type?expansions=AssetType.attributes
X-Api-Key: {{read-only-token}}

### Upserts new asset type
PUT {{api-server}}/v2/asset-types?expansions=AssetType.attributes
X-Api-Key: {{read-write-token}}
Content-Type: application/json

{
  "attributes": [
    {
      "enable": true,
      "name": "switch_state",
      "subtype": "input",
      "type": "inputs-and-switches",
      "translation": {
        "de": "Schalterzustand",
        "en": "Switch state"
      }
    },
    {
      "enable": true,
      "name": "switch",
      "subtype": "output",
      "type": "inputs-and-switches",
      "translation": {
        "de": "Schalter",
        "en": "Switch"
      },
      "map": [
        {
          "value": 0,
          "text": "OFF"
        },
        {
          "value": 1,
          "text": "ON"
        }
      ]
    }
  ],
  "custom": false,
  "icon": null,
  "name": "abb_free_at_home_switch_sensor",
  "translation": {
    "de": "ABB-free@home Schaltsensor",
    "en": "ABB-free@home Switch sensor"
  },
  "urldoc": "https://apim.eu.mybuildings.abb.com/adtg-api/v1/graphiql/?doc#definition-Channel",
  "vendor": "ABB"
}

### Insert new asset type
POST {{api-server}}/v2/asset-types?expansions=attributes
X-Api-Key: {{read-write-token}}
Content-Type: application/json

{
  "vendor": "vendor",
  "custom": true,
  "name": "weather_location",
  "translation": {
    "de": "Das ist eine deutsche Beschreibung",
    "en": "This is an english description",
    "it": "Questa è una descrizione italiana",
    "fr": "Ceci est une description français"
  },
  "icon": "weather",
  "urldoc": "urldoc",
  "model": "model",
  "attributes": [
    {
      "enable": true,
      "name": "test",
      "subtype": "input"
    }
  ]
}

### Update new asset type
PUT {{api-server}}/v2/asset-types/weather_location
X-Api-Key: {{read-write-token}}
Content-Type: application/json

{
  "vendor": "vendor",
  "custom": true,
  "name": "weather_location",
  "translation": {
    "de": "Das ist eine deutsche Beschreibung",
    "en": "This is an english description",
    "it": "Questa è una descrizione italiana",
    "fr": "Ceci est une description français"
  },
  "icon": "weather",
  "urldoc": "urldoc",
  "model": "model"
}