### [Dashboards] List dashboards with expansion (read-only)
GET {{api-server}}/v2/dashboards?expansions=Dashboard.widgets HTTP/1.1
X-Api-Key: {{read-only-token}}

### [Dashboards] Create a new dashboard with public flag (read–write)
POST {{api-server}}/v2/dashboards HTTP/1.1
X-Api-Key: {{read-write-token}}
Content-Type: application/json

{
  "name": "Example Dashboard",
  "projectId": "99",
  "userId": "1",
  "public": true
}
