### Get all data
GET http://localhost:8084/v2/data

### Get all data based on asset id
GET http://localhost:8084/v2/data?assetId=125

### Get all data based on subtype
GET http://localhost:8084/v2/data?dataSubtype=input

### Get all data based on asset type
GET http://localhost:8084/v2/data?assetTypeName=VIRTUAL Battery

