### Get all data
GET http://localhost:8084/v2/data

### Get all data based on asset id
GET http://localhost:8084/v2/data?assetId=125

### Get all data based on subtype
GET http://localhost:8084/v2/data?dataSubtype=input

### Get all data based on asset type
GET http://localhost:8084/v2/data?assetTypeName=VIRTUAL Battery

### Get data trends
GET http://localhost:8084/v2/data-trends?assetTypeName=VIRTUAL Battery&fromDate=2022-07-30T20:00:00.000%2B02:00&toDate=2022-07-30T21:00:00.000%2B02:00

### Get data aggs
GET http://localhost:8084/v2/aggregated-data?assetId=9002

### Get data aggs with timestamp
GET http://localhost:8084/v2/aggregated-data?assetId=9002&fromDate=2022-08-08T14:00:00.0%2B02:00&toDate=2022-08-08T15:00:11.0%2B02:00
