### Get data trends with size
GET {{api-server}}/v2/data-trend/17049?dataSubtype=input&attributeName=energy&fromDate=2024-09-18T11:58:00.000%2B02:00&toDate=2024-10-18T00:05:00.0%2B02:00&size=1
X-Api-Key: {{read-only-token}}

### Get data aggs with sum with size
GET {{api-server}}/v2/data-trend-aggregated/17049?attributeName=energy&dataSubtype=input&aggregationRaster=1d&fromDate=2024-09-14T23:50:00.0%2B02:00&toDate=2024-10-18T00:05:00.0%2B02:00&size=1
X-Api-Key: {{read-only-token}}

### Get data aggs with cusum
GET {{api-server}}/v2/data-trend-aggregated/17049?attributeName=energy&dataSubtype=input&aggregationRaster=1d&fromDate=2024-09-14T23:50:00.0%2B02:00&toDate=2024-10-18T00:05:00.0%2B02:00&sumMethod=cusum
X-Api-Key: {{read-only-token}}
