### Get all data
GET {{api-server}}/v2/data
X-Api-Key: {{read-only-token}}

### Get all data based on asset id
GET {{api-server}}/v2/data?assetId=927&
X-Api-Key: {{read-only-token}}

### Get all data based on subtype
GET {{api-server}}/v2/data?dataSubtype=input
X-Api-Key: {{read-only-token}}

### Get all data based on asset type
GET {{api-server}}/v2/data?assetTypeName=VIRTUAL Battery
X-Api-Key: {{read-only-token}}

### Put data
PUT {{api-server}}/v2/data
X-Api-Key: {{read-write-token}}

  {
    "assetId": 17534,
    "subtype": "input",
    "data": {
      "value": null
    }
  }

### Put data
PUT {{api-server}}/v2/data
X-Api-Key: {{read-write-token}}

{
     "data": {
       "value":99
         },
"subtype":"input",
"assetId":17501
}

### Put data bulk
PUT {{api-server}}/v2/data-bulk
X-Api-Key: {{read-write-token}}

  [
  {
    "assetId": 8514,
    "subtype": "input",
    "data": {
    "brightness": 222
    },
    "clientReference": "42"
  }
  ]