### Send mail
POST {{api-server}}/v2/send-mail
X-Api-Key: {{read-write-token}}
Content-Type: application/json

{
  "recipients": [
    "andreas.goebel@eliona.io"
  ],
  "subject": "This is an example message",
  "content": "<h1>Hello world!</h1><p>Das ist ein Test</p>",
  "attachments" : [
    {
      "name": "example.gif",
      "encoding": "base64",
      "contentType": "image/png",
      "content": "iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII="
    }
  ]
}

### Get mail status
GET {{api-server}}/v2/message-receipts/9
X-Api-Key: {{read-only-token}}
