### [Nodes] List nodes (read-only)
GET {{api-server}}/v2/nodes HTTP/1.1
X-Api-Key: {{read-only-token}}

### [Nodes] Create a new node with detailed information (read–write)
POST {{api-server}}/v2/nodes HTTP/1.1
X-Api-Key: {{read-write-token}}
Content-Type: application/json

{
  "ident": "fef0a0d3-acad-4611-ac03-1fd842d72505",
  "assetId": 4711,
  "vendor": "VendorName",
  "model": "NodeModelX",
  "description": "Edge node for West Plant",
  "enable": true
}

### [Nodes] Get node by ident (read-only)
GET {{api-server}}/v2/nodes/fef0a0d3-acad-4611-ac03-1fd842d72505 HTTP/1.1
X-Api-Key: {{read-only-token}}

### [Nodes] Update node with additional optional fields (read–write)
PUT {{api-server}}/v2/nodes/fef0a0d3-acad-4611-ac03-1fd842d72505 HTTP/1.1
X-Api-Key: {{read-write-token}}
Content-Type: application/json

{
  "ident": "fef0a0d3-acad-4611-ac03-1fd842d72505",
  "assetId": 4711,
  "vendor": "VendorName",
  "model": "NodeModelX",
  "description": "Updated description for node at West Plant",
  "enable": true
}
