### [Tags] List all tags (read-only)
GET {{api-server}}/v2/tags HTTP/1.1
X-Api-Key: {{read-only-token}}

### [Tags] Create or update a tag with extra parameters (read–write)
PUT {{api-server}}/v2/tags HTTP/1.1
X-Api-Key: {{read-write-token}}
Content-Type: application/json

{
  "name": "Support",
  "colorId": 3,
  "custom": true
}

### [Tags] Get a tag by name (read-only)
GET {{api-server}}/v2/tags/Support HTTP/1.1
X-Api-Key: {{read-only-token}}