### [Widget types] List widget types (read-only)
GET {{api-server}}/v2/widget-types HTTP/1.1
X-Api-Key: {{read-only-token}}

### [Widget types] Create or update a new widget type with multiple elements (read–write)
PUT {{api-server}}/v2/widget-types HTTP/1.1
X-Api-Key: {{read-write-token}}
Content-Type: application/json

{
  "name": "Weather",
  "custom": true,
  "translation": {
    "en": "Weather Widget",
    "de": "Wetter Widget"
  },
  "icon": "weather",
  "elements": [
    {
      "sequence": 1,
      "category": "weather",
      "config": {
        "variant": "todayAndForecast"
      }
    },
    {
      "sequence": 2,
      "category": "trend",
      "config": {
        "timeSpan": "24h"
      }
    }
  ]
}